# Generated by Django 6.0 on 2026-05-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_alter_appointment_doctor_and_more'),
        ('billing', '0001_initial'),
        ('patients', '0002_alter_patient_address_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='appointment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='appointments.appointment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='patients.patient'),
        ),
    ]
