# Generated by Django 6.0 on 2026-05-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_alter_appointment_doctor_and_more'),
        ('billing', '0002_bill_appointment_alter_bill_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='appointments.appointment'),
        ),
    ]
